name: main

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5.7, 3.6.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
        sudo tar -xvf go1.12.7.linux-amd64.tar.gz
        sudo mv go /usr/local
        export PATH="${PATH}:/usr/local/go/bin"

    - name: Test with pytest
      run: |
        pytest
